print("Program starting.")
print("\n")
word1 = input("Insert a closed compound word: ")
print("The word you inserted is ", word1 , "and in reverse it is ", word1[::-1] , ".", sep="'")
print(f"The inserted word length is {len(word1)}")
print("Last character is " , word1[-1::] , ".", sep="'")
print("\n")
print("Take substring from the inserted word by inserting...")
s = int(input("1) Starting point: "))
e = int(input("2) Ending point: "))
st = int(input("3) Step size: "))
print("The word ", word1 , " sliced to the defined substring is ", word1[s:e:st] , ".", sep="'")
print("Program ending.")